require("./view");              // VIEW组件
require("./content");           // CONTENT组件
require("./bar");               // BAR组件
require("./tabs");              // TABS组件
require("./modal");             // MODAL组件
require("./iframe");            // IFRAME组件
require("./slider");            // SLIDER组件
require("./confirm");           // CONFIRM组件
require("./select");            // SELECT组件
require("./star");              // STAR组件