require("./view");              // VIEW组件
require("./content");           // CONTENT组件
require("./header");			// HEADER组件
require("./footer");			// FOOTER组件
require("./tabs");              // TABS组件
require("./modal");             // MODAL组件
require("./iframe");            // IFRAME组件
require("./slider");            // SLIDER组件
require("./confirm");           // CONFIRM组件
require("./select");            // SELECT组件
require("./router");			// 路由返回组件
require("./lefter");            // LEFTER倒计时组件
require("./expand");			// EXPAND展开收缩控件
require("./timer");				// TIMER时间选择控件
